Document: dirbuster
Title: Debian dirbuster Manual
Author: <insert document author here>
Abstract: This manual describes what dirbuster is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/dirbuster/dirbuster.sgml.gz

Format: postscript
Files: /usr/share/doc/dirbuster/dirbuster.ps.gz

Format: text
Files: /usr/share/doc/dirbuster/dirbuster.text.gz

Format: HTML
Index: /usr/share/doc/dirbuster/html/index.html
Files: /usr/share/doc/dirbuster/html/*.html
